version: '3'

services:
    db:
        image: "postgres"
        container_name: "db"
        environment: 
            - POSTGRES_PASSWORD=django 
            - POSTGRES_USER=django
            - POSTGRES_DB=healthcheck
        # ports:
        #     - "5432:5432"
        volumes:
            - ./dbdata:/var/lib/postgresql/data
    django:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
        env_file: ./.env
        volumes:
            - .:/app
        ports:
            - "8000:8000"
              #expose:
              #            - 8000
        depends_on:
            - db
