version: '3'

services:
    db:
        image: "postgres"
        container_name: "db"
        environment: 
            - POSTGRES_PASSWORD=django 
            - POSTGRES_USER=django
            - POSTGRES_DB=healthcheck
        volumes:
            - ./dbdata:/var/lib/postgresql/data
    redis:
        container_name: "redis"
        image: redis:alpine
    django:
        container_name: "django"
        build:
            context: .
            dockerfile: ./Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        env_file: ./.env
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        links:
            - db
            - redis
    celery:
        container_name: "celery"
        image: celery:4.4
        build: .
        env_file: ./.env
        volumes:
            - .:/app
        # command: celery -A healthcheck worker -l info
        command: watchmedo auto-restart --directory=./ --pattern=*tasks.py --recursive -- celery -A healthcheck worker -l info
        depends_on:
            - db
            - redis
        links:
            - redis
            - db
            - django
    celery-beat:
        container_name: "celery-beat"
        image: celery:4.4
        build: .
        env_file: ./.env
        volumes:
            - .:/app
        # command: celery -A healthcheck beat -l info
        command: watchmedo auto-restart --directory=./ --pattern=*tasks.py --recursive -- celery -A healthcheck beat -l info
        depends_on:
            - db
            - redis
        links:
            - redis
            - db
            - django

