name: Run Tests

on:
    push:
        branches: [develop, master]
    pull_request:
        branches: [develop, master]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.7.7
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -e .
                  pip install -r requirements-dev.txt
            - name: Run tests
              run: |
                  flake8
                  black --check .
                  isort -c -rc .
                  DJANGO_SETTINGS_MODULE=healthcheck.settings.test python manage.py makemigrations --dry-run | grep 'No changes detected' || (echo 'There are changes which require migrations.' && exit 1)
                  python manage.py test
